### PR TITLE
Added cmake build files

### LINKED ISSUE #13: Set up CMake
I think we want to use CMake to create the visual studio files and download additional dependencies like Box2d. If there is a CMake expert who wants to help us out that would be great!

### PR DESCRIPTION
**Pull request by sgavil**
Added cmake build, tested in Visual Studio 2019. 
- New source or header files should be added to `src/sources.cmake`
- New third party libraries can be added to extern and automatically get linked when regenerating the .sln

closes #13

### CODE REVIEW

**Comment by michaelplzno** [comment]
Hey Sergio, 

One of the big pushes with this task is to get the CMAKE system to download the external library box2d from github as part of the initial build process. Will it do this?

**Comment by sgavil** [comment]
> Hey Sergio,
> 
> One of the big pushes with this task is to get the CMAKE system to download the external library box2d from github as part of the initial build process. Will it do this?

Hi Michael, 
Now atm no, if you want that we could consider to use Conan as package manager or I can either make the packages download from cmake directly.

**Comment by vozdeckyl** [comment]
> > Hey Sergio,
> > One of the big pushes with this task is to get the CMAKE system to download the external library box2d from github as part of the initial build process. Will it do this?
> 
> Hi Michael, Now atm no, if you want that we could consider to use Conan as package manager or I can either make the packages download from cmake directly.

Hi, what about using git submodules? Do you think that would solve this issue?

**Comment by sgavil** [comment]
> > > Hey Sergio,
> > > One of the big pushes with this task is to get the CMAKE system to download the external library box2d from github as part of the initial build process. Will it do this?
> > 
> > 
> > Hi Michael, Now atm no, if you want that we could consider to use Conan as package manager or I can either make the packages download from cmake directly.
> 
> Hi, what about using git submodules? Do you think that would solve this issue?

Yeah, that would be another valid option too. Btw @michaelplzno, would you mind adding the label `hacktoberfest-accepted` to this PR so it counts for hacktoberfest?

**Pull request merged**
