### PR TITLE
Gravity On Off

### PR DESCRIPTION
**Pull request by LOBO8525**
Well, there are 2 committer but its both me...like i said, im new to this and i had problems to commit with Visual Studio XD
And my code could be a little sloppy.

### CODE REVIEW

**Comment by michaelplzno** [comment]
Thanks will look at this shortly!

**Comment by michaelplzno** [comment]
So I've looked at this a little bit, there are two issues: one is that it seems you replaced all the files with exact copies of the files so I sort of have to go through line by line and check that nothing changed, did you redo everything into tabs instead of spaces? That's a nono.

Also not to be persnickety but can you put the global var about gravity in the physics file instead of blokaroka.h? 

When you get those things taken care of, checking in only what is changed, and moving the gravity bool to physics I'll push it through. Thanks!

**Comment by LOBO8525** [comment]
Yeah, the push didn't work at the beginning. So I uploaded all important files to my branch manually.Sorry for that, like I said, I'm new to all of this. I got it now, I hope.No? Why would I redo everything? Does it look like it?I will fork it again and push only the changes.I have no problem with you being persnickety, it's your project :)Ty for looking over it.Btw. did someone try to fix the  issue with the blocks overlapping ?
-------- Ursprüngliche Nachricht --------Von: Michael Silverman <notifications@github.com> Datum: 11.08.20  22:22  (GMT+01:00) An: michaelplzno/Blokaroka <Blokaroka@noreply.github.com> Cc: LOBO8525 <h-a-kizilkaya@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [michaelplzno/Blokaroka] Gravity On Off (#21) 
So I've looked at this a little bit, there are two issues: one is that it seems you replaced all the files with exact copies of the files so I sort of have to go through line by line and check that nothing changed, did you redo everything into tabs instead of spaces? That's a nono.
Also not to be persnickety but can you put the global var about gravity in the physics file instead of blokaroka.h?
When you get those things taken care of, checking in only what is changed, and moving the gravity bool to physics I'll push it through. Thanks!

**Comment by michaelplzno** [comment]
I'm new to managing a project so I'm not 100% sure I'm doing this right either, we can learn together! I'm gonna close this branch and let you try again, I think that's the right thing to do!

I don't use visual studio to manage commits and updates, I actually use tortisesvn to check in code, which is free and good, you might want to check it out.

**Comment by michaelplzno** [comment]
Also, the bloks overlapping have not been fixed, there are still some cases where the edges render incorrectly. I recommend you run the build and try to experiment with the layering depth system when blocks are close to one another and see if you can get a feel for the issue, its kind of complicated!

**Comment by LOBO8525** [comment]
we use TortoiseSVN at work, but that visual studio commit looks good too.  I like testing diffrent programs.

**Comment by michaelplzno** [comment]
sure, whatever works, its just several files were rewritten so I didn't want to check them in if they weren't actually changed.

**Comment by LOBO8525** [comment]
maybe i should do the easy issues/adds first, before i try the overlapping issue. 

I thought it would just upload the files that are actually changed by committing everyting, just like in SVN...

**Comment by LOBO8525** [comment]
You can see the changes that I made to my branch right?
LOBO8525/BlokarokaMaybe you could look at the changes before I make a pull request. When you have time ofc.
-------- Ursprüngliche Nachricht --------Von: Michael Silverman <notifications@github.com> Datum: 11.08.20  23:53  (GMT+01:00) An: michaelplzno/Blokaroka <Blokaroka@noreply.github.com> Cc: LOBO8525 <h-a-kizilkaya@gmx.de>, Author <author@noreply.github.com> Betreff: Re: [michaelplzno/Blokaroka] Gravity On Off (#21) 
sure, whatever works, its just several files were rewritten so I didn't want to check them in if they weren't actually changed.

**Comment by michaelplzno** [comment]
I can see the changes, the problem is that due to the way you are checking it in it is marking the entire physics file as modified as opposed to just the bits you changed, so I have to go through the entire file to see what you actually changed. Your branch also has the entire licence file marked as rewritten as well as the readme and some other stuff you didn't actually change. So in your branch you need to revert some of the files you didn't actually change. For the physics files, you need to save your changes and revert the rest of the code to the current version. I'm not sure if you redid whitespace or what but its marked physics.cpp as entirely new in your branch.

Also on further review, you seem to be resetting the gravity every frame based on the button, that's also a mistake. Can you make it so that when the menu option is pressed it sets the gravity one time as opposed to setting the gravity inside the physics update function?

**Comment by michaelplzno** [comment]
I think you may need to create a new fork from your end and then copy in your revisions, then delete the old forked branch? I'm not entirely sure how to fix it, but it has to be on your end somehow.

**Pull request closed without merging**
